(function(){
"use strict";
const $=s=>document.querySelector(s);
const svgNS="http://www.w3.org/2000/svg";
const children=[];
const esc=v=>String(v||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function val(id){return $(id)?.value.trim()||""}
function checked(id){return Boolean($(id)?.checked)}
function personLabel(name,age){return [name,age?`${age} th`:""].filter(Boolean).join(" · ")||"?"}
function addChild(data={name:"",age:"",gender:"male",deceased:false}){children.push(data);renderChildInputs()}
function renderChildInputs(){const box=$("#childList");box.innerHTML="";children.forEach((c,i)=>{const row=document.createElement("div");row.className="child-row";row.innerHTML=`<div class="field"><label>Nama anak ${i+1}</label><input data-k="name" data-i="${i}" value="${esc(c.name)}" placeholder="Nama"></div><div class="field"><label>Usia</label><input data-k="age" data-i="${i}" type="number" min="0" value="${esc(c.age)}"></div><div class="field"><label>Gender</label><select data-k="gender" data-i="${i}"><option value="male" ${c.gender==="male"?"selected":""}>L</option><option value="female" ${c.gender==="female"?"selected":""}>P</option></select></div><button type="button" data-remove="${i}" aria-label="Hapus anak"><i class="fa-solid fa-trash"></i></button>`;box.appendChild(row)});box.querySelectorAll("input,select").forEach(el=>el.addEventListener("input",()=>{children[+el.dataset.i][el.dataset.k]=el.value}));box.querySelectorAll("[data-remove]").forEach(btn=>btn.addEventListener("click",()=>{children.splice(+btn.dataset.remove,1);renderChildInputs();generate()}))}
function node(x,y,gender,label,opt={}){const g=document.createElementNS(svgNS,"g");g.setAttribute("transform",`translate(${x} ${y})`);const shape=document.createElementNS(svgNS,gender==="female"?"circle":"rect");if(gender==="female"){shape.setAttribute("cx","0");shape.setAttribute("cy","0");shape.setAttribute("r","22")}else{shape.setAttribute("x","-22");shape.setAttribute("y","-22");shape.setAttribute("width","44");shape.setAttribute("height","44")}shape.setAttribute("fill",opt.client?"#334155":"#fff");shape.setAttribute("stroke","#0f172a");shape.setAttribute("stroke-width","3");g.appendChild(shape);if(opt.deceased){const a=document.createElementNS(svgNS,"line");a.setAttribute("x1","-20");a.setAttribute("y1","-20");a.setAttribute("x2","20");a.setAttribute("y2","20");a.setAttribute("stroke","#0f172a");a.setAttribute("stroke-width","3");const b=a.cloneNode();b.setAttribute("x1","20");b.setAttribute("x2","-20");g.append(a,b)}const t=document.createElementNS(svgNS,"text");t.setAttribute("x","0");t.setAttribute("y","38");t.setAttribute("text-anchor","middle");t.setAttribute("font-size","12");t.setAttribute("font-family","Arial, sans-serif");t.setAttribute("fill","#0f172a");t.textContent=label;g.appendChild(t);return g}
function line(svg,x1,y1,x2,y2,dash=false){const l=document.createElementNS(svgNS,"line");Object.entries({x1,y1,x2,y2}).forEach(([k,v])=>l.setAttribute(k,v));l.setAttribute("stroke","#0f172a");l.setAttribute("stroke-width","3");if(dash)l.setAttribute("stroke-dasharray","8 7");svg.appendChild(l);return l}
function couple(svg,x1,x2,y,downY){line(svg,x1+22,y,x2-22,y);const mid=(x1+x2)/2;line(svg,mid,y,mid,downY);return mid}
function dataPerson(prefix,gender){return{gender,name:val(`#${prefix}Name`),age:val(`#${prefix}Age`),deceased:checked(`#${prefix}Dead`)}}
function generate(){const svg=$("#genogramSvg");svg.innerHTML="";svg.setAttribute("viewBox","0 0 1000 720");const client={gender:val("#clientGender")||"female",name:val("#clientName"),age:val("#clientAge"),deceased:false,client:true};const partner={gender:val("#partnerGender")||"male",name:val("#partnerName"),age:val("#partnerAge"),deceased:checked("#partnerDead")};const cp=dataPerson("clientParent1","male"),cm=dataPerson("clientParent2","female"),pp=dataPerson("partnerParent1","male"),pm=dataPerson("partnerParent2","female");const gps=[dataPerson("gp1","male"),dataPerson("gp2","female"),dataPerson("gp3","male"),dataPerson("gp4","female")];const title=document.createElementNS(svgNS,"text");title.setAttribute("x","40");title.setAttribute("y","38");title.setAttribute("font-size","22");title.setAttribute("font-weight","700");title.setAttribute("font-family","Arial,sans-serif");title.textContent="GENOGRAM 3 GENERASI";svg.appendChild(title);
// Generasi I
[[130,250,gps[0],gps[1]],[570,690,gps[2],gps[3]]].forEach(([x1,x2,a,b])=>{svg.append(node(x1,105,a.gender,personLabel(a.name,a.age),a));svg.append(node(x2,105,b.gender,personLabel(b.name,b.age),b));couple(svg,x1,x2,105,165)});
// Garis ke orang tua
line(svg,190,165,190,220);line(svg,190,220,320,220);line(svg,320,220,320,255);line(svg,630,165,630,220);line(svg,630,220,760,220);line(svg,760,220,760,255);
svg.append(node(320,280,cp.gender,personLabel(cp.name,cp.age),cp));svg.append(node(440,280,cm.gender,personLabel(cm.name,cm.age),cm));const cMid=couple(svg,320,440,280,365);
svg.append(node(700,280,pp.gender,personLabel(pp.name,pp.age),pp));svg.append(node(820,280,pm.gender,personLabel(pm.name,pm.age),pm));const pMid=couple(svg,700,820,280,365);
// Klien dan pasangan
line(svg,cMid,365,cMid,430);line(svg,pMid,365,pMid,430);svg.append(node(400,455,client.gender,personLabel(client.name,client.age),client));svg.append(node(660,455,partner.gender,personLabel(partner.name,partner.age),partner));couple(svg,400,660,455,535);
// Saudara opsional divisualkan sebagai info keluarga inti
const sibC=val("#clientSibling"),sibP=val("#partnerSibling");if(sibC){const t=document.createElementNS(svgNS,"text");t.setAttribute("x","250");t.setAttribute("y","345");t.setAttribute("font-size","12");t.setAttribute("text-anchor","middle");t.textContent=`Saudara klien: ${sibC}`;svg.appendChild(t)}if(sibP){const t=document.createElementNS(svgNS,"text");t.setAttribute("x","850");t.setAttribute("y","345");t.setAttribute("font-size","12");t.setAttribute("text-anchor","middle");t.textContent=`Saudara pasangan: ${sibP}`;svg.appendChild(t)}
// Anak
const count=Math.max(children.length,1),start=530-(count-1)*60;line(svg,Math.max(130,start),535,Math.min(930,start+(count-1)*120),535);children.forEach((c,i)=>{const x=start+i*120;line(svg,x,535,x,590);svg.append(node(x,615,c.gender,personLabel(c.name,c.age),c))});if(!children.length){const t=document.createElementNS(svgNS,"text");t.setAttribute("x","530");t.setAttribute("y","610");t.setAttribute("text-anchor","middle");t.setAttribute("font-size","13");t.textContent="Belum ada data anak";svg.appendChild(t)}
// Garis serumah
const house=document.createElementNS(svgNS,"rect");house.setAttribute("x","350");house.setAttribute("y","405");house.setAttribute("width","360");house.setAttribute("height","280");house.setAttribute("rx","8");house.setAttribute("fill","none");house.setAttribute("stroke","#64748b");house.setAttribute("stroke-width","2");house.setAttribute("stroke-dasharray","8 7");svg.insertBefore(house,svg.firstChild.nextSibling);
const legend=document.createElementNS(svgNS,"text");legend.setAttribute("x","40");legend.setAttribute("y","700");legend.setAttribute("font-size","12");legend.textContent="□ Laki-laki   ○ Perempuan   ● Klien   ✕ Meninggal   --- Serumah";svg.appendChild(legend)}
async function svgBlob(){const svg=$("#genogramSvg");const xml=new XMLSerializer().serializeToString(svg);return new Blob([xml],{type:"image/svg+xml;charset=utf-8"})}
async function pngBlob(){const blob=await svgBlob(),url=URL.createObjectURL(blob),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});const canvas=document.createElement("canvas");canvas.width=1600;canvas.height=1152;const ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);return await new Promise(r=>canvas.toBlob(r,"image/png"))}
async function copyImage(){try{const blob=await pngBlob();if(navigator.clipboard&&window.ClipboardItem){await navigator.clipboard.write([new ClipboardItem({"image/png":blob})]);alert("Genogram berhasil disalin sebagai gambar.")}else{throw new Error("Clipboard gambar tidak didukung")}}catch(e){console.error(e);alert("Browser belum mendukung salin gambar. Gunakan tombol Unduh PNG.")}}
async function download(){const blob=await pngBlob(),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="genogram-3-generasi.png";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function init(){addChild({name:"Anak 1",age:"",gender:"male"});addChild({name:"Anak 2",age:"",gender:"female"});$("#addChild").addEventListener("click",()=>addChild());$("#generateBtn").addEventListener("click",generate);$("#copyBtn").addEventListener("click",copyImage);$("#downloadBtn").addEventListener("click",download);document.querySelectorAll("#genogramForm input,#genogramForm select").forEach(el=>el.addEventListener("change",generate));generate()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
